// Lista de criptomonedas soportadas — espejo de COINGECKO_SYMBOL_TO_ID del backend (/api/prices)
export const CRYPTO_LIST = [
  { id: 'bitcoin', symbol: 'BTC', name: 'Bitcoin', color: 'text-warn' },
  { id: 'ethereum', symbol: 'ETH', name: 'Ethereum', color: 'text-info' },
  { id: 'solana', symbol: 'SOL', name: 'Solana', color: 'text-compare' },
  { id: 'binancecoin', symbol: 'BNB', name: 'BNB', color: 'text-caution' },
  { id: 'ripple', symbol: 'XRP', name: 'Ripple', color: 'text-muted-foreground' },
  { id: 'cardano', symbol: 'ADA', name: 'Cardano', color: 'text-info' },
  { id: 'dogecoin', symbol: 'DOGE', name: 'Dogecoin', color: 'text-caution' },
  { id: 'avalanche-2', symbol: 'AVAX', name: 'Avalanche', color: 'text-short' },
  { id: 'polkadot', symbol: 'DOT', name: 'Polkadot', color: 'text-pink-500' },
  { id: 'chainlink', symbol: 'LINK', name: 'Chainlink', color: 'text-info' },
  { id: 'litecoin', symbol: 'LTC', name: 'Litecoin', color: 'text-foreground' },
  { id: 'matic-network', symbol: 'MATIC', name: 'Polygon (MATIC)', color: 'text-compare' },
  { id: 'polygon-ecosystem-token', symbol: 'POL', name: 'Polygon (POL)', color: 'text-compare' },
  { id: 'tron', symbol: 'TRX', name: 'TRON', color: 'text-short' },
  { id: 'cosmos', symbol: 'ATOM', name: 'Cosmos', color: 'text-compare' },
  { id: 'near', symbol: 'NEAR', name: 'NEAR Protocol', color: 'text-long' },
  { id: 'aptos', symbol: 'APT', name: 'Aptos', color: 'text-teal-400' },
  { id: 'arbitrum', symbol: 'ARB', name: 'Arbitrum', color: 'text-info' },
  { id: 'optimism', symbol: 'OP', name: 'Optimism', color: 'text-short' },
  { id: 'injective-protocol', symbol: 'INJ', name: 'Injective', color: 'text-info' },
  { id: 'sui', symbol: 'SUI', name: 'Sui', color: 'text-info' },
  { id: 'celestia', symbol: 'TIA', name: 'Celestia', color: 'text-compare' },
  { id: 'shiba-inu', symbol: 'SHIB', name: 'Shiba Inu', color: 'text-warn' },
  { id: 'pepe', symbol: 'PEPE', name: 'Pepe', color: 'text-long' },
  { id: 'the-open-network', symbol: 'TON', name: 'Toncoin', color: 'text-info' },
  { id: 'uniswap', symbol: 'UNI', name: 'Uniswap', color: 'text-pink-400' },
  { id: 'stellar', symbol: 'XLM', name: 'Stellar', color: 'text-muted-foreground' },
  { id: 'monero', symbol: 'XMR', name: 'Monero', color: 'text-warn' },
  { id: 'ethereum-classic', symbol: 'ETC', name: 'Ethereum Classic', color: 'text-long' },
  { id: 'bitcoin-cash', symbol: 'BCH', name: 'Bitcoin Cash', color: 'text-long' },
  { id: 'filecoin', symbol: 'FIL', name: 'Filecoin', color: 'text-info' },
  { id: 'algorand', symbol: 'ALGO', name: 'Algorand', color: 'text-muted-foreground' },
  { id: 'vechain', symbol: 'VET', name: 'VeChain', color: 'text-info' },
  { id: 'hedera-hashgraph', symbol: 'HBAR', name: 'Hedera', color: 'text-muted-foreground' },
  { id: 'aave', symbol: 'AAVE', name: 'Aave', color: 'text-compare' },
  { id: 'maker', symbol: 'MKR', name: 'Maker', color: 'text-teal-400' },
  { id: 'the-sandbox', symbol: 'SAND', name: 'The Sandbox', color: 'text-info' },
  { id: 'decentraland', symbol: 'MANA', name: 'Decentraland', color: 'text-short' },
  { id: 'eos', symbol: 'EOS', name: 'EOS', color: 'text-muted-foreground' },
  { id: 'tezos', symbol: 'XTZ', name: 'Tezos', color: 'text-info' },
  { id: 'crypto-com-chain', symbol: 'CRO', name: 'Cronos', color: 'text-info' },
  { id: 'quant-network', symbol: 'QNT', name: 'Quant', color: 'text-muted-foreground' },
  { id: 'elrond-erd-2', symbol: 'EGLD', name: 'MultiversX', color: 'text-info' },
  { id: 'thorchain', symbol: 'RUNE', name: 'THORChain', color: 'text-teal-400' },
  { id: 'pancakeswap-token', symbol: 'CAKE', name: 'PancakeSwap', color: 'text-caution' },
  { id: 'theta-token', symbol: 'THETA', name: 'Theta', color: 'text-info' },
  { id: 'axie-infinity', symbol: 'AXS', name: 'Axie Infinity', color: 'text-info' },
  { id: 'internet-computer', symbol: 'ICP', name: 'Internet Computer', color: 'text-compare' },
  { id: 'the-graph', symbol: 'GRT', name: 'The Graph', color: 'text-compare' },
  { id: 'immutable-x', symbol: 'IMX', name: 'Immutable', color: 'text-info' },
  { id: 'render-token', symbol: 'RENDER', name: 'Render', color: 'text-short' },
  { id: 'fetch-ai', symbol: 'FET', name: 'Fetch.ai', color: 'text-info' },
  { id: 'kaspa', symbol: 'KAS', name: 'Kaspa', color: 'text-teal-400' },
  { id: 'blockstack', symbol: 'STX', name: 'Stacks', color: 'text-compare' },
  { id: 'bittensor', symbol: 'TAO', name: 'Bittensor', color: 'text-muted-foreground' },
  { id: 'dogwifcoin', symbol: 'WIF', name: 'dogwifhat', color: 'text-caution' },
  { id: 'bonk', symbol: 'BONK', name: 'Bonk', color: 'text-caution' },
  { id: 'floki', symbol: 'FLOKI', name: 'Floki', color: 'text-warn' },
  { id: 'jupiter-exchange-solana', symbol: 'JUP', name: 'Jupiter', color: 'text-long' },
  { id: 'pyth-network', symbol: 'PYTH', name: 'Pyth Network', color: 'text-compare' },
  { id: 'sei-network', symbol: 'SEI', name: 'Sei', color: 'text-short' },
  { id: 'ondo-finance', symbol: 'ONDO', name: 'Ondo', color: 'text-muted-foreground' },
  { id: 'ethena', symbol: 'ENA', name: 'Ethena', color: 'text-info' },
  { id: 'worldcoin-wld', symbol: 'WLD', name: 'Worldcoin', color: 'text-muted-foreground' },
  { id: 'lido-dao', symbol: 'LDO', name: 'Lido DAO', color: 'text-warn' },
  { id: 'curve-dao-token', symbol: 'CRV', name: 'Curve', color: 'text-caution' },
  { id: 'gala', symbol: 'GALA', name: 'Gala', color: 'text-muted-foreground' },
  { id: 'flow', symbol: 'FLOW', name: 'Flow', color: 'text-long' },
  { id: 'chiliz', symbol: 'CHZ', name: 'Chiliz', color: 'text-short' },
  { id: 'basic-attention-token', symbol: 'BAT', name: 'Basic Attention', color: 'text-warn' },
  { id: '1inch', symbol: '1INCH', name: '1inch', color: 'text-short' },
  { id: 'sushi', symbol: 'SUSHI', name: 'SushiSwap', color: 'text-pink-400' },
  { id: 'yearn-finance', symbol: 'YFI', name: 'yearn.finance', color: 'text-info' },
  { id: 'arweave', symbol: 'AR', name: 'Arweave', color: 'text-muted-foreground' },
  { id: 'iota', symbol: 'IOTA', name: 'IOTA', color: 'text-muted-foreground' },
  { id: 'zcash', symbol: 'ZEC', name: 'Zcash', color: 'text-caution' },
];

export const COMMODITIES = [
  { id: 'gold', symbol: 'XAUUSD', name: 'Oro/USD', color: 'text-caution' },
];

export const ALL_ASSETS = [...CRYPTO_LIST, ...COMMODITIES];

// Niveles de Fibonacci
export const FIBONACCI_LEVELS = [
  { level: 0, label: '0%' },
  { level: 0.236, label: '23.6%' },
  { level: 0.382, label: '38.2%' },
  { level: 0.5, label: '50%' },
  { level: 0.618, label: '61.8%' },
  { level: 0.786, label: '78.6%' },
  { level: 1, label: '100%' },
  { level: 1.272, label: '127.2%' },
  { level: 1.618, label: '161.8%' },
];

// Patrones de Trading con imágenes y pasos
